server:
  port: 8090

spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jdbcclient
    username: admin
    password: 123456
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

